Pewe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls')),
    path('coursetaked/', include('coursetaked.urls')),
    path('activity/', include('activity.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

activity/urls.py
from django.urls import include, path
from .views import *

app_name = 'activity'
urlpatterns = [
    path('', home, name='home'),
    path('activityform', activityform, name='activityform'),
    path('saveactivity', saveactivity),
    path('deleteactivity-<str:activity_name>', deleteActivity, name='deleteactivity'),
    path('memberform-<str:activity_name>', memberform, name='memberform'),
    path('savemember-<str:activity_name>', savemember, name='savemember'),
    path('deletemember-<str:activity_name>.<str:member_name>', deleteMember, name='deletemember'),
]

activity/models.py
from django.db import models

# Create your models here.

class Activity(models.Model):
    activity_name = models.CharField(max_length=30, primary_key=True)
    description = models.CharField(max_length=100, blank=True, null=False)

class Member(models.Model):
    name = models.CharField(max_length=30, primary_key=True)

class MemberActivity(models.Model):
    name = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='memberactivitys', null=False)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, related_name='activitymembers', null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'activity'], name='composite unique')
        ]

activity/forms.py
from django import forms
from .models import *

class Activity_Form(forms.ModelForm):
	class Meta:
		model = Activity
		fields = '__all__'

	error_messages = {
		'required' : 'Please Type'
	}

class Member_Form(forms.Form):
	name = forms.CharField(max_length=30)

	def nameError(self, msg):
		self.add_error('name', msg)

activity/views.py
from django.shortcuts import render
from .forms import *
from django.http import HttpResponseRedirect
from .models import *


# Create your views here.

ttl = 'Pewe'
response = {}

def home(request):
	activities = Activity.objects.all()
	response = {'ttl': ttl + ' Activities'
					, 'activities': activities
					, 'title': 'Activities'}
	return render(request, 'activities.html', response)


def activityform(request):
	message = request.GET.get('message', '')
	response = {'ttl': ttl + ' Activity Form'
					, 'title': 'Activity Form'
					, 'message': message
					, 'action': 'saveactivity'
					, 'input_form': Activity_Form}
	return render(request, 'form.html', response)


def saveactivity(request):
	form = Activity_Form(request.POST or None)
	if (form.is_valid() and request.method == 'POST'):
		form.save()
		return HttpResponseRedirect('activityform?message=' + form.cleaned_data['activity_name'] + ' succesfully have been added')
	else:
		response = {'ttl': ttl + ' Activity Form'
						,'title': 'Activity Form'
						,'action': 'saveactivity'
						, 'message' : 'Your input is invalid'
						, 'input_form': form}
		return render(request, 'form.html', response)

def deleteActivity(request, activity_name):
	Activity.objects.get(activity_name=activity_name).delete()
	return HttpResponseRedirect('/activity/')

def memberform(request, activity_name):
	message = request.GET.get('message', '')
	response = {'ttl': ttl + ' Member Form'
					,'title': 'Member Form'
					, 'activity_name' : activity_name
					, 'message': message
					, 'input_form': Member_Form}
	return render(request, 'memberform.html', response)

def savemember(request, activity_name):
	form = Member_Form(request.POST or None)
	if (form.is_valid() and request.method == 'POST'):
		name = form.cleaned_data.get('name')

		member = None
		try:
			member = Member.objects.get(name=name)
		except:
			member = Member.objects.create(name=name)

		activity = Activity.objects.get(activity_name=activity_name)
		try:
			MemberActivity.objects.create(name=member, activity=activity)
		except:
			form.nameError(msg="Member have been added before")
			response = {'ttl': ttl + ' Member Form'
					,'title': 'Member Form'
					, 'activity_name' : activity_name
					, 'message' : 'Your input is invalid'
					, 'input_form': form}
			return render(request, 'memberform.html', response)

		message = name + ' succesfully have been added'
		response = {'ttl': ttl + ' Member Form'
					,'title': 'Member Form'
					, 'activity_name' : activity_name
					, 'message': message
					, 'input_form': Member_Form}
		return render(request, 'memberform.html', response)

	else:
		response = {'ttl': ttl + ' Member Form'
					,'title': 'Member Form'
					, 'activity_name' : activity_name
					, 'message' : 'Your input is invalid'
					, 'input_form': form}
		return render(request, 'memberform.html', response)

def deleteMember(request, activity_name, member_name):
	MemberActivity.objects.get(name=member_name, activity=activity_name).delete()
	return HttpResponseRedirect('/activity/')

activity/templates/activities.html
{% extends 'page2.html' %}
{% load static %}

{% block header %}
<div class="col-xs-1 text-center">
    <a href="{% url 'activity:activityform' %}"><button class = 'btn btn-info'>Add Activity</button></a>
</div>
{% endblock %}

{% block page_content %}

{% for activity in activities %}
<div class="py-5" >
    <div class="container text-center">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>{{activity.activity_name}}</h3>
                    </div>
                    <div class="card-body">
                    {% if activity.activitymembers.all %}
                    <h4 class="h-modification">Peserta</h4>
                    {% for member in activity.activitymembers.all %}
                        <p>{{member.name.name}}
                        <a class="btn-danger"href="{% url 'activity:deletemember' activity_name=activity.activity_name member_name=member.name.name %}">
                            kick 
                        </a>
                        </p>
                    {% endfor %}
                    {% endif %}
                    {% if activity.description != '' %}
                        <h4 class="h-modification">Deskripsi</h4>
                        <p>{{activity.description}}</p>
                    {% endif %}
                    <a href="{% url 'activity:memberform' activity_name=activity.activity_name %}"><button class = 'btn btn-warning'>
                        Add Member
                    </button></a>
                    <br><br>
                    <a href="{% url 'activity:deleteactivity' activity_name=activity.activity_name %}"><button class="btn btn-danger">
                        Hapus
                    </button></a>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

activity/templates/form.html
{% extends 'page.html' %}
{% load static %}
{% block page_content %}

<div style="display: block;">
    <a href="{% url 'activity:home'%}"><button class="btn btn-success">
        Back
    </button></a>
    <br><br>
    <form action={{action}} method="POST">
        {% csrf_token %}
        {{ input_form.as_p }}
        <input type="submit" value="Submit" class="btn btn-warning">
    </form>
    {% if message != '' %}
    <br>
    {{message}}
    {% endif %}
</div>
{% endblock %}

activity/templates/memberform.html
{% extends 'page.html' %}
{% load static %}
{% block page_content %}

<div style="display: block;">
    <a href="{% url 'activity:home'%}"><button class="btn btn-success">
        Back
    </button></a>
    <br><br>
    <form action={% url 'activity:savemember' activity_name=activity_name %} method="POST">
        {% csrf_token %}
        {{ input_form.as_p }}
        <input type="submit" value="Submit" class="btn btn-warning">
    </form>
    {% if message != '' %}
    <br>
    {{message}}
    {% endif %}
</div>
{% endblock %}