Pewe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls')),
    path('coursetaked/', include('coursetaked.urls')),
    path('activity/', include('activity.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

coursetaked/urls.py
from django.urls import include, path
from .views import *

app_name = 'coursetaked'
urlpatterns = [
    path('', home, name='home'),
    path('courseform', courseform, name='courseform'),
    path('coursedetail/<str:course_name>', coursedetail, name="coursedetail"),
    path('removecourse/<str:course_name>', removecourse, name="removecourse"),
    path('savecourse', savecourse),
]

coursetaked/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Course(models.Model):
	course_name = models.CharField(max_length=30, primary_key=True)
	instructor = models.CharField(max_length=30)
	semester = models.PositiveIntegerField(validators=[MinValueValidator(1)])
	description = models.TextField(max_length=100, blank=True)

coursetaked/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

class Input_Form(forms.ModelForm):
	class Meta:
		model = Course
		fields = ['course_name', 'instructor', 'semester', 'description']

	error_messages = {
		'required' : 'Please Type'
	}
	
	def clean_semester(self):
		semester = self.cleaned_data.get('semester')
		if semester < 1:
			raise ValidationError('Zero semester is not exist')
		return semester

coursetaked/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import *

# Create your views here.
ttl = 'Pewe'
response = {}

def home(request):
	courses = Course.objects.all()
	response = {'ttl' : ttl + ' Course Taked List'
				,'title' : 'Course Taking List'
				, 'courses' : courses}
	return render(request, 'courselist.html', response)

def courseform(request):
	message = request.GET.get('message', '')
	response = {'ttl' : ttl + ' Course Taked Form'
					,'title' : 'Course Taking Form'
					,'input_form' : Input_Form
					, 'message' : message}
	return render(request, 'formcourse.html', response)

def savecourse(request):
	form = Input_Form(request.POST or None)
	if (form.is_valid() and request.method == 'POST'):
		form.save()
		return HttpResponseRedirect('/coursetaked/courseform?message=' + form.cleaned_data['course_name'] + ' have been added')
	else:
		response = {'ttl' : ttl + ' Course Taked Form'
					,'title' : 'Course Taking Form'
					,'input_form' : form
					, 'message' : 'Your input is invalid'}
		return render(request, 'formcourse.html', response)

def coursedetail(request, course_name):
	course = Course.objects.get(course_name=course_name)
	response = {'ttl' : ttl + ' Course Detail'
				,'title' : 'Course Detail'
				,'course' : course}
	return render(request, 'coursedetail.html', response)

def removecourse(request, course_name):
	Course.objects.get(course_name=course_name).delete()
	return HttpResponseRedirect('/coursetaked')

coursetaked/templates/coursedetail.html
{% extends 'page.html' %}
{% load static %}
{% block page_content %}

<div style="display: block;">
    <h4>Name</h4> <p>{{ course.course_name }}</p>
    <br><br>
    <h4>Instructor</h4> <p>{{ course.instructor }}</p>
    <br><br>
    <h4>Semester</h4> <p>{{ course.semester }}</p>
    <br><br>
    <h4>Description</h4>
    <br>
    <p>{{ course.description }}</p>
    <br><br>
    <a href="{% url 'coursetaked:removecourse' course_name=course.course_name%}"><button class="btn btn-danger">
        Remove
    </button></a>
    <a href="{% url 'coursetaked:home'%}"><button class="btn btn-success">
        Back
    </button></a>
</div>

{% endblock %}

coursetaked/templates/courselist.html
{% extends 'page.html' %}
{% load static %}
{% block page_content %}

<div style="display: block;">
    <a href="{% url 'coursetaked:courseform' %}"><button class = 'btn btn-warning'>Add Course</button></a>
    {% if courses %}
        <br>
        <br>
        <table class="table table-striped">
            <tr>
            <th>Course Name</th>
            <th>Instructor</th>
            <th>Semester</th>
            </tr>
            {% for course in courses %}
                <tr>
                    <td><a href="{% url 'coursetaked:coursedetail' course_name=course.course_name %}">
                        {{ course.course_name }}
                    </a></td>
                    <td>{{ course.instructor }}</td>
                    <td>{{ course.semester }}</td>
                    <td><a href="{% url 'coursetaked:removecourse' course_name=course.course_name%}"><button class = 'btn btn-danger'>
                        Hapus
                    </button></a></td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

</div>
{% endblock %}

coursetaked/templates/formcourse.html
{% extends 'page.html' %}
{% load static %}
{% block page_content %}

<div style="display: block;">
    <a href="{% url 'coursetaked:home'%}"><button class="btn btn-success">
        Back
    </button></a>
    <br><br>
    <form action="savecourse" method="POST">
        {% csrf_token %}
        {{ input_form.as_p }}
        <input type="submit" value="Submit" class="btn btn-warning">
    </form>
    {% if message != '' %}
    <br>
    {{message}}
    {% endif %}
</div>
{% endblock %}