Pewe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls')),
    path('coursetaked/', include('coursetaked.urls')),
    path('activity/', include('activity.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story1/urls.py
from django.urls import include, path
from .views import *

app_name = 'story1'
urlpatterns = [
    path('', home, name='home'),
]

story4/urls.py
from django.urls import include, path
from .views import *

app_name = 'story4'
urlpatterns = [
    path('', home, name='home'),
    path('work', work, name='work'),
    path('profile', profile, name='profile'),
]

story7/urls.py
from django.urls import include, path
from .views import *

app_name = 'story7'
urlpatterns = [
    path('', home, name='home'),
]

story8/urls.py
from django.urls import include, path
from .views import *

app_name = 'story8'
urlpatterns = [
    path('', home, name='home'),
    path('searchbook', searchBook, name='searchbook')
]

Pewe/templates/page.html
{% extends 'webframe.html' %}
{% load static %}
{% block content %}

<div class="py-5 overlay-item page-background">
    <div class="flex-container">
      <div class="row" style="height: 100vmax;">
        <div class="col-md-12">
          <h1 class="text-center mb-4">{{title}}</h1>
          <div class="row align-items-start justify-content-center">
            {% block page_content %} {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Pewe/templates/page2.html
{% extends 'webframe.html' %}
{% load static %}
{% block content %}

<div class="py-5 overlay-item page-background">
    <div class="flex-container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center mb-4">{{title}}</h1>
          {% block header %} {% endblock %}
          <br>
          <div class="row align-items-start justify-content-center px-5">
            {% block page_content %} {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Pewe/templates/webframe.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ ttl }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customcss/default.css' %}">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block head_additional %}{% endblock%}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container"> <a class="navbar-brand text-primary" href="{% url 'story4:home' %}">
        <i class="fa d-inline fa-lg fa-stop-circle"></i>
        <b class="web-title">Pewe</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar4">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar4">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="{% url 'story4:profile' %}">My Profile</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'story4:work' %}">My Work</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'coursetaked:home' %}">Course Taking</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'activity:home' %}">Activity</a> </li>
          <div class="dropdown">
            <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Story
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <a class="dropdown-item" href="{% url 'story1:home' %}">Story 1 (Old Profile)</a>
              <a class="dropdown-item" href="{% url 'story7:home' %}">Accordion Test</a>
              <a class="dropdown-item" href="{% url 'story8:home' %}">Ajax Test</a>
            </div>
          </div>
          <div class="dropdown">
            <button class="btn dropdown-toggle userinfo" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if user.is_authenticated %}
                Halo {{ user.first_name }}
              {% else %}
                Please login
              {% endif %}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'story9:logout' %}">Log Out</a>
              {% else %}
                <a class="dropdown-item" href="{% url 'story9:login' %}">Log in</a>
                <a class="dropdown-item" href="{% url 'story9:signup' %}">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>
  <div id="content">
      {% block content %}{% endblock %}
  </div>
</body>
</html>